#ifndef _VERSION_H_
#define _VERSION_H_

#define GIT_MAJOR_VERSION $GIT_MAJOR_VERSION$
#define GIT_MINOR_VERSION $GIT_MINOR_VERSION$
#define GIT_REVISION $GIT_REVISION$
#define GIT_SHORT_HASH "$GIT_SHORT_HASH$"
#define GIT_LONG_HASH "$GIT_LONG_HASH$"
#define GIT_COMMITS_SINCE_TAG $GIT_COMMITS_SINCE_TAG$

#endif // _VERSION_H_

